from enum import Enum
from dataclasses import dataclass, field
from typing import Dict, Any

class Action(Enum):
    """
    Defines authorized trades.
    """
    BUY = 1
    SELL = -1
    WAIT = 0

@dataclass
class MonkeySignal:
    """
    Standard format for decision takes by agent (Monkey).
    Object send to the notion database.
    """
    monkey_name: str
    action: Action
    confidence: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """
        Quant validation: Automatic security executed at object creation.
        """
        if not(0.0 <= self.confidence <= 1.0):
            raise ValueError(
                f"Fatal error ({self.monkey_name}): "
                f"Confidence should be between 0.0 and 1.0, Receive: {self.confidence}"
            )

@dataclass
class TradePlan:
    """
    Structured outcome generated by the RiskMonkey after consensus.
    Contains clear risk/reward metrics and conditional scenarios.
    """
    ticker: str
    direction: str          # "BUY" | "SELL" | "WAIT"
    entry_price: float
    take_profit: float      # 0.0 si direction == "WAIT"
    stop_loss: float        # 0.0 si direction == "WAIT"
    risk_reward: float      # (tp - entry) / (entry - sl), 0.0 si WAIT
    confidence: float       # score de confiance 0.0 → 1.0
    atr_value: float        # valeur ATR utilisée pour le calcul
    scenarios: list[str]    # propositions conditionnelles
    agents_log: str         # repris du champ Log_Agents de l'orchestrateur
    generated_at: str       # datetime ISO UTC au moment de la génération

    def to_markdown(self) -> str:
        """
        Returns a readable markdown summary for terminal display or Notion.
        """
        color = "🟢" if self.direction == "BUY" else "🔴" if self.direction == "SELL" else "⚪"
        md = []
        md.append(f"## TradePlan — {self.ticker} — {color} {self.direction}")
        md.append("")
        md.append("| Field | Value |")
        md.append("|---|---|")
        md.append(f"| **Entry Price** | {self.entry_price:.4f} |")
        md.append(f"| **Take Profit** | {self.take_profit:.4f} |")
        md.append(f"| **Stop Loss** | {self.stop_loss:.4f} |")
        md.append(f"| **Risk/Reward** | {self.risk_reward:.2f} |")
        md.append(f"| **Confidence** | {self.confidence:.2f} |")
        md.append(f"| **ATR Val** | {self.atr_value:.4f} |")
        md.append(f"| **Timestamp** | {self.generated_at} |")
        md.append("")
        md.append("### Scenarios")
        for sc in self.scenarios:
            md.append(f"- {sc}")
        md.append("")
        md.append("### Agent Logs")
        md.append(f"`{self.agents_log}`")
        return "\n".join(md)